name: transformers
channels:
  - defaults
dependencies:
  - blas=1.0
  - boto3=1.24.28
  - botocore=1.27.59
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - filelock=3.9.0
  - flit-core=3.8.0
  - future=0.18.3
  - huggingface_hub=0.10.1
  - idna=3.4
  - jmespath=0.10.0
  - joblib=1.1.1
  - libcxx=14.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libprotobuf=3.20.3
  - libuv=1.44.2
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - pytorch=1.12.1
  - pyyaml=6.0
  - readline=8.2
  - regex=2022.7.9
  - requests=2.28.1
  - s3transfer=0.6.0
  - sacremoses=0.0.43
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.1
  - tk=8.6.12
  - tqdm=4.65.0
  - transformers=2.1.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
